version: '3.8'

services:
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    image: book_catalog:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sit722_82c_user:4zLiJsbkhG9VGcdRE97ozhFqLWUUHIhB@dpg-crj3b9qj1k6c73fjc3b0-a.singapore-postgres.render.com/sit722_82c
    depends_on:
      - postgres

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    image: inventory_management:latest
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://sit722_82c_user:4zLiJsbkhG9VGcdRE97ozhFqLWUUHIhB@dpg-crj3b9qj1k6c73fjc3b0-a.singapore-postgres.render.com/sit722_82c
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: sit722_82c_user
      POSTGRES_PASSWORD: 4zLiJsbkhG9VGcdRE97ozhFqLWUUHIhB
      POSTGRES_DB: sit722_82c
    ports:
      - "5432:5432"